### ISSUE TITLE
Crash sur les recherches

### ISSUE THREAD

**Issue by foux** [KiLMaN/T411-Torznab#13]
Bonjour,

Depuis quelques temps j'ai un crash systématique sur les recherches : 

```
debug: Query : New Girl
debug:  t=tvsearch, cat=5030,5040, extended=1, apikey=12345, offset=0, limit=50, q=New Girl, season=5, ep=10
debug:  url=http://api.t411.ch/torrents/search/New Girl?term[45][]=972&term[46][]=947&offset=0&limit=50, Authorization=99664297:68:dc804c99477921042a9e100894653540
debug: Got 0 torrents
debug:  t=tvsearch, cat=5030,5040, extended=1, apikey=12345, offset=0, limit=50, tvdbid=279536, tvmazeid=3606, season=1, ep=7
debug: Requested TvMaez Id : 3606
debug: TvMaze Cache for 3606 empty, querying tvMaze
debug: Got informations from TvRage
/opt/t411-torznav/node_modules/node-cache/lib/node_cache.js:297
      return key.length;
                ^
TypeError: Cannot read property 'length' of undefined
    at NodeCache.module.exports.NodeCache._getKeyLength (/opt/t411-torznav/node_modules/node-cache/lib/node_cache.js:297:17)
    at NodeCache.module.exports.NodeCache.set (/opt/t411-torznav/node_modules/node-cache/lib/node_cache.js:112:34)
    at NodeCache.set (/opt/t411-torznav/node_modules/node-cache/lib/node_cache.js:3:59)
    at Object.tvRageResult (/opt/t411-torznav/server.js:244:15)
    at Request._callback (/opt/t411-torznav/tvmaze.js:22:3)
    at Request.self.callback (/opt/t411-torznav/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/opt/t411-torznav/node_modules/request/request.js:1082:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/opt/t411-torznav/node_modules/request/request.js:1009:12)
```

Une idée d'ou ça peut venir?
Merci

**Comment by KiLMaN** [comment]
Ca devrais être fixé, je l'avais deja corrigé mais pas mit sur Github.
Peux tu vérifier ?

**Comment by foux** [comment]
Je pourrais tester en début d'après-midi. Merci!

**Comment by foux** [comment]
Ça a l'air OK. Merci!
