### ISSUE TITLE
Impossible de se connecter depuis ce matin

### ISSUE THREAD

**Issue by foux** [KiLMaN/T411-Torznab#14]
Bonjour,
Depuis ce matin j'ai l'erreur suivante : 

```
█▓▒░foux@genplex░▒▓██▓▒░ jeu. mars 24 10:18:19
/opt/t411-torznav> node server.js
info: Starting T411 proxy
info: Running in : /opt/t411-torznav
info: Trying to log into T411 with user : 'xxxxx'
/opt/t411-torznav/server.js:584
            _logger.err("Failed to login to T411 : Please verify your credentials in 'c
                    ^
TypeError: undefined is not a function
    at Request.callbackLoginT411 [as _callback] (/opt/t411-torznav/server.js:584:12)
    at Request.self.callback (/opt/t411-torznav/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/opt/t411-torznav/node_modules/request/request.js:1082:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/opt/t411-torznav/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

J'ai vérifié mes identifiants qui sont bons. Y'a t'il un problème sur l'API?

**Comment by foux** [comment]
C'est apparement un problème sur T411, je ferme pour le moment

**Comment by KiLMaN** [comment]
J'ai aussi corrigé un bug d'affichage a l'instant. L'erreur devrais être plus lisible

**Comment by foux** [comment]
En effet, la nouvelle erreur est beaucoup mieux :+1:

**Comment by Juuust1** [comment]
Bonjour, tous fonctionnais bien il y a quelque mois et jusqu'a une réinstallation de mon NAS aujourd'hui, j'obtient la même erreur...
Y a-t-il une solution ?
Merci

**Comment by KiLMaN** [comment]
As tu vérifié que tu utilise la dernière version du logiciel ? 
As tu vérifié tes identifiant dans le fichier de configuration ?

**Comment by Juuust1** [comment]
J'ai pris la version dispo en dl sur ton github et oui mes identifiants sont correct j'ai vérifié...
Tu parle peut-être de la version de node ? J'utilise la v4, la dernière dispo sur mon nas synology.

**Comment by Juuust1** [comment]
J'ai pris la version dispo en dl sur ton github et oui mes identifiants sont correct j'ai vérifié...
Tu parle peut-être de la version de node ? J'utilise la v4, la dernière dispo sur mon nas synology.

**Comment by KiLMaN** [comment]
Pour le moment je n'ai pas de solution. A tu plus d'informations concernant l'erreur ? Peut tu essayer d'utiliser l'api t411 à partir du site https://api.t411.li ?

**Comment by Juuust1** [comment]
Voici l'erreur complète que j'obtiens : 

```
justin@NAS-Justin:/var/services/homes/admin$ node server.js 
info: Starting T411 proxy
info: Running in : /volume1/homes/admin
info: Trying to log into T411 with user : '<xxxxx>'
/volume1/homes/admin/server.js:666
				_logger.err("Failed to login to T411 : Please verify your credentials in 'config.json'");
				        ^

TypeError: _logger.err is not a function
    at Request.callbackLoginT411 [as _callback] (/volume1/homes/admin/server.js:666:13)
    at Request.self.callback (/volume1/homes/admin/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/volume1/homes/admin/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/volume1/homes/admin/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
```

Pour ce qui est de l'api t411 je ne sais pas trop quoi en faire, je suis vraiment novice dans ce domaine...

Merci pour ton aide :)
