### ISSUE TITLE
Error logging t411

### ISSUE THREAD

**Issue by billbob-space** [KiLMaN/T411-Torznab#25]
Hello,
I can't login t411 with your docker.

Here the error message 
```javascript
info: Trying to log into T411 with user : 'XXXXX'
/usr/src/app/server.js:598
				_logger.err("Failed to login to T411 : Please verify your credentials in 'config.json'");
				        ^

TypeError: _logger.err is not a function
    at Request.callbackLoginT411 [as _callback] (/usr/src/app/server.js:598:13)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
```

**Comment by billbob-space** [comment]
It's my fault I was desactivate from the tracker ... forgot my issue. Sorry
