### ISSUE TITLE
pb with last version of python ?

### ISSUE THREAD

**Issue by gentleman35** [KiLMaN/T411-Torznab#28]
Hi !
It's not my first install but this time, after the last update of python : 

ash-4.3# node server.js
module.js:427
    throw err;
    ^

SyntaxError: /volume1/homes/admin/config.json: Unexpected token <
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:424:27)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/volume1/homes/admin/server.js:5:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by KiLMaN** [comment]
Please verify the content of your config.json. It seems that you have a "<"  that is not supported by the file.

Le 30 déc. 2016, à 22:23, gentleman35 <notifications@github.com<mailto:notifications@github.com>> a écrit:

Hi !
It's not my first install but this time, after the last update of python :

ash-4.3# node server.js
module.js:427
throw err;
^

SyntaxError: /volume1/homes/admin/config.json: Unexpected token <
at Object.parse (native)
at Object.Module._extensions..json (module.js:424:27)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/volume1/homes/admin/server.js:5:14)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)

**Comment by gentleman35** [comment]
Hi

After npm uninstall .. all was ok !
So i closed issue

Thanks for contact !

De : Brice Gaulupeau [mailto:notifications@github.com]
Envoyé : mardi 3 janvier 2017 17:41
À : KiLMaN/T411-Torznab <T411-Torznab@noreply.github.com>
Cc : gentleman35 <jackpopot@hotmail.fr>; State change <state_change@noreply.github.com>
Objet : Re: [KiLMaN/T411-Torznab] pb with last version of python ? (#28)

Please verify the content of your config.json. It seems that you have a "<" that is not supported by the file.

Le 30 déc. 2016, à 22:23, gentleman35 <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>> a écrit:

Hi !
It's not my first install but this time, after the last update of python :

ash-4.3# node server.js
module.js:427
throw err;
^

SyntaxError: /volume1/homes/admin/config.json: Unexpected token <
at Object.parse (native)
at Object.Module._extensions..json (module.js:424:27)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/volume1/homes/admin/server.js:5:14)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
