### ISSUE TITLE
SyntaxError 

### ISSUE THREAD

**Issue by Takounie** [KiLMaN/T411-Torznab#29]
Hello everybody,

I have an issue when I try to run the server.js node 
```
vps:~/T411-Torznab# node server.js
module.js:591
    throw err;
    ^

SyntaxError: /root/T411-Torznab/config.json: Unexpected token < in JSON at position 87
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/T411-Torznab/server.js:5:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

I'm on Ubuntu 16.04, and I also looked at https://github.com/KiLMaN/T411-Torznab/issues/9#issuecomment-182935503 as it looked similar but I found nothing that could help

If someone has any idea on how to solve that, he would be my savior ;)

**Comment by KiLMaN** [comment]
It's a error with the configuration file, 
Please remove the two lines :  
```
"debugVerified":<debugVerified>,
"onlyVerified":<onlyVerified>
```
and replace with :	
```
"debugVerified":false,
"onlyVerified":true
```
It's an error with the default config file since we added docker .

**Comment by Takounie** [comment]
Thanks a lot, it's working now :)
