### ISSUE TITLE
node server.js

### ISSUE THREAD

**Issue by youngcesar** [KiLMaN/T411-Torznab#31]
hello i have an issue when i launch node server.js

`module.js:485
    throw err;
          ^
SyntaxError: /home/youngcesar/T411-Torznab/config.json: Unexpected token <
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/youngcesar/T411-Torznab/server.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`
config.json is good credentials modified

thank you

**Comment by KiLMaN** [comment]
Please check #28 #29
It's now fixed on the main repo
