### ISSUE TITLE
issue ubuntu 16.04

### ISSUE THREAD

**Issue by AmazingRedPanda** [KiLMaN/T411-Torznab#33]
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
node server.js 
module.js:428
    throw err;
    ^

SyntaxError: /try/T411-Torznab-master/config.json: Unexpected token g
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:425:27)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/try/T411-Torznab-master/server.js:5:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

**Comment by KiLMaN** [comment]
Please check that your configuration file is well formed. It's looks like you have a "g"  somewhere on the file
