### ISSUE TITLE
Cannot find module 'underscore'

### ISSUE THREAD

**Issue by darkh89** [KiLMaN/T411-Torznab#41]
Dear Team, 

I update the server.js

and I got this error: 

Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/sonar/T411/server.js:12:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

any idea ?

Best regards

**Comment by ghost** [comment]
you forgot to do **npm install** I guess
