### ISSUE TITLE
T411-torznab on qnap nas

### ISSUE THREAD

**Issue by bioshock47** [KiLMaN/T411-Torznab#9]
Hello,

I would like to know if you have information about how install your indexer on a qnap nas?

I try to make the manipulation you make but it's not working.

I'm not familiar about coding, i'm a new beginner in nas.

Thanks a lot for your help.

Regards,

**Comment by KiLMaN** [comment]
What is you problem exactly ? Have you been able to install nodejs ? If not you can follow the instruction on this website http://tech.panshin.me/technology/qnap-node-js-installation.html to install it.

Can you please post more details (screen-shoots) ?

**Comment by bioshock47** [comment]
I just did the instruction on the website you gave me, but the npm command is not reconize
for npm version or npm install i have the message "command not found"

**Comment by daviddp4** [comment]
Hello,

I'm in similar situation with my qnap NAS, I've tried to follow the instruction but i'm having an error with the "npm install" command, the install of Nodejs is ok...

[~] # ls /share/MD0_DATA/temp/T411-Torznab-master/
config.json.sample  logger.js           server.js
Dockerfile          package.json        startup
.gitignore          README.md           tvmaze.js
[~] # cd /share/MD0_DATA/temp/T411-Torznab-master/
[/share/MD0_DATA/temp/T411-Torznab-master] # npm install

module.js:340
    throw err;
              ^
Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at /share/MD0_DATA/.qpkg/nodejs/node/bin/npm:18:11
    at Object.<anonymous> (/share/MD0_DATA/.qpkg/nodejs/node/bin/npm:86:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Thanks for your answer...

**Comment by KiLMaN** [comment]
@daviddp4  Did you read my previous post ? http://tech.panshin.me/technology/qnap-node-js-installation.html Please follow it and see if it changes anything.

**Comment by daviddp4** [comment]
@KiLMaN Thank you soo much, all work fine now !!! I've just had a problem with a tv show but it works with an another one...When I have the problem, the proxy crash and i have to reload the node server.js again. I'try to give you the error code.
Thanks!!!

**Comment by bioshock47** [comment]
how can you have the detail about the "error cannot find module npmlog"? Me it just said command not found, with no such details.

**Comment by KiLMaN** [comment]
@bioshock47 I can't help you more if i don't see what you have done / what you get from the command line. 
Maybe @daviddp4 can help you now that it's working for him.

**Comment by daviddp4** [comment]
@bioshock47 Did you installed the Nodejs.qpkg paket and followed the steps of the link: http://tech.panshin.me/technology/qnap-node-js-installation.html
You must to be in the folder where are the files to run the npm install command.

**Comment by yotechno** [comment]
@bioshock47 For me it was a problem of path. Check in your path if there is the path to npm (do command echo $PATH | tr : \n).
If not in it, add it and try again (to add: export PATH=$PATH:/share/CACHEDEV1_DATA/lib/node/bin
)

**Comment by bioshock47** [comment]
OK i try again and it's not working

I try to use container station on my qnap which contain docker

i install the T411 torznab, and i have the following messages

npm ERR! Linux 3.12.6  
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"  
npm ERR! node v5.3.0  
npm ERR! npm  v3.5.2  
npm ERR! code ELIFECYCLE  
npm ERR! T411-torznab@0.0.0 start: `node server.js`  
npm ERR! Exit status 1  
npm ERR!  
npm ERR! Failed at the T411-torznab@0.0.0 start script 'node server.js'.  
npm ERR! Make sure you have the latest version of node.js and npm installed.  
npm ERR! If you do, this is most likely a problem with the T411-torznab package,  
npm ERR! not with npm itself.  
npm ERR! Tell the author that this fails on your system:  
npm ERR!     node server.js  
npm ERR! You can get information on how to open an issue for this project with:  
npm ERR!     npm bugs T411-torznab  
npm ERR! Or if that isn't available, you can get their info via:  
npm ERR!     npm owner ls T411-torznab  
npm ERR! There is likely additional logging output above.                                                                                                                                                                                        

npm ERR! Please include the following file with any support request:  
npm ERR!     /usr/src/app/npm-debug.log     

I install node on the countainer too, but i have the same messages.

Thanks a lot for your help and patience.

Regards,
